



server:
  port: 8180

#第一个数据源（多数据源将会在后面介绍,primary表示为第一个数据源）
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/bftglwz?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWD:123456}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 6000
      pool-name: DatebookHikariCP

mybatis:
  mapper-locations: classpath:mappers/*.xml


logging:
  config: classpath:log/logback.xml
  level:
    com.data.report.mapper : debug


bankcode:
  code:
    "001": 工商银行
    "002": 农业银行
    "003": 中国银行
    "004": 建设银行
    "005": 交通银行
    "006": 招商银行
    "007": 华夏银行
    "008": 邮储银行
    "009": 民生银行
    "010": 光大银行
    "011": 中信银行
    "012": 浦发银行
    "013": 广发银行
    "014": 兴业银行
    "015": 深发银行
    "016": 广州银行
    "017": 广州农商
    "018": 上海银行
    "019": 平安银行
    "021": 北京银行

errcode:
  code:
    "910RE": "渠道返回超时"
    "91096": "渠道其他错误"
    "210J4": "姓名格式错误"
    "21082": "身份证格式错误"
    "21055": "CVN2格式错误"
    "01031": "不支持银行卡"
    "000J9": "发卡方异常"
    "000J7": "银行卡状态异常"
    "00082": "身份证号错误"
    "00081": "银行卡号错误"
    "00064": "验证不通过"
    "00061": "验证次数超限"
    "00054": "卡已过有效期"
    "00051": "账户额度不足"
    "210J2": "手机号格式错误"
    "000J8": "不允许的交易"
    "000J4": "姓名与银行预留信息不符"
    "000J2": "手机号与银行预留信息不符"
    "00070": "银行卡未开通银联无卡业务"
    "00063": "证件号与银行预留信息不符"





